# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_network import *
from .identity import *
from .member import *
from .network import *
from .provider import *
from .token import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_zerotier.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_zerotier.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "zerotier",
  "mod": "index/identity",
  "fqn": "pulumi_zerotier",
  "classes": {
   "zerotier:index/identity:Identity": "Identity"
  }
 },
 {
  "pkg": "zerotier",
  "mod": "index/member",
  "fqn": "pulumi_zerotier",
  "classes": {
   "zerotier:index/member:Member": "Member"
  }
 },
 {
  "pkg": "zerotier",
  "mod": "index/network",
  "fqn": "pulumi_zerotier",
  "classes": {
   "zerotier:index/network:Network": "Network"
  }
 },
 {
  "pkg": "zerotier",
  "mod": "index/token",
  "fqn": "pulumi_zerotier",
  "classes": {
   "zerotier:index/token:Token": "Token"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "zerotier",
  "token": "pulumi:providers:zerotier",
  "fqn": "pulumi_zerotier",
  "class": "Provider"
 }
]
"""
)
