# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'NetworkAssignIpv4',
    'NetworkAssignIpv6',
    'NetworkAssignmentPool',
    'NetworkRoute',
    'GetNetworkAssignIpv4Result',
    'GetNetworkAssignIpv6Result',
    'GetNetworkAssignmentPoolResult',
    'GetNetworkRouteResult',
]

@pulumi.output_type
class NetworkAssignIpv4(dict):
    def __init__(__self__, *,
                 zerotier: Optional[bool] = None):
        if zerotier is not None:
            pulumi.set(__self__, "zerotier", zerotier)

    @property
    @pulumi.getter
    def zerotier(self) -> Optional[bool]:
        return pulumi.get(self, "zerotier")


@pulumi.output_type
class NetworkAssignIpv6(dict):
    def __init__(__self__, *,
                 rfc4193: Optional[bool] = None,
                 sixplane: Optional[bool] = None,
                 zerotier: Optional[bool] = None):
        if rfc4193 is not None:
            pulumi.set(__self__, "rfc4193", rfc4193)
        if sixplane is not None:
            pulumi.set(__self__, "sixplane", sixplane)
        if zerotier is not None:
            pulumi.set(__self__, "zerotier", zerotier)

    @property
    @pulumi.getter
    def rfc4193(self) -> Optional[bool]:
        return pulumi.get(self, "rfc4193")

    @property
    @pulumi.getter
    def sixplane(self) -> Optional[bool]:
        return pulumi.get(self, "sixplane")

    @property
    @pulumi.getter
    def zerotier(self) -> Optional[bool]:
        return pulumi.get(self, "zerotier")


@pulumi.output_type
class NetworkAssignmentPool(dict):
    def __init__(__self__, *,
                 end: Optional[str] = None,
                 start: Optional[str] = None):
        """
        :param str end: The last address in the assignment rule. This must be the highest number in the pool. end must also be accompanied by start.
        :param str start: The first address in the assignment rule. This must be the lowest number in the pool. `start` must also be accompanied by `end`.
        """
        if end is not None:
            pulumi.set(__self__, "end", end)
        if start is not None:
            pulumi.set(__self__, "start", start)

    @property
    @pulumi.getter
    def end(self) -> Optional[str]:
        """
        The last address in the assignment rule. This must be the highest number in the pool. end must also be accompanied by start.
        """
        return pulumi.get(self, "end")

    @property
    @pulumi.getter
    def start(self) -> Optional[str]:
        """
        The first address in the assignment rule. This must be the lowest number in the pool. `start` must also be accompanied by `end`.
        """
        return pulumi.get(self, "start")


@pulumi.output_type
class NetworkRoute(dict):
    def __init__(__self__, *,
                 target: str,
                 via: Optional[str] = None):
        """
        :param str target: Network to route for
        :param str via: Gateway address
        """
        pulumi.set(__self__, "target", target)
        if via is not None:
            pulumi.set(__self__, "via", via)

    @property
    @pulumi.getter
    def target(self) -> str:
        """
        Network to route for
        """
        return pulumi.get(self, "target")

    @property
    @pulumi.getter
    def via(self) -> Optional[str]:
        """
        Gateway address
        """
        return pulumi.get(self, "via")


@pulumi.output_type
class GetNetworkAssignIpv4Result(dict):
    def __init__(__self__, *,
                 zerotier: Optional[bool] = None):
        if zerotier is not None:
            pulumi.set(__self__, "zerotier", zerotier)

    @property
    @pulumi.getter
    def zerotier(self) -> Optional[bool]:
        return pulumi.get(self, "zerotier")


@pulumi.output_type
class GetNetworkAssignIpv6Result(dict):
    def __init__(__self__, *,
                 rfc4193: Optional[bool] = None,
                 sixplane: Optional[bool] = None,
                 zerotier: Optional[bool] = None):
        if rfc4193 is not None:
            pulumi.set(__self__, "rfc4193", rfc4193)
        if sixplane is not None:
            pulumi.set(__self__, "sixplane", sixplane)
        if zerotier is not None:
            pulumi.set(__self__, "zerotier", zerotier)

    @property
    @pulumi.getter
    def rfc4193(self) -> Optional[bool]:
        return pulumi.get(self, "rfc4193")

    @property
    @pulumi.getter
    def sixplane(self) -> Optional[bool]:
        return pulumi.get(self, "sixplane")

    @property
    @pulumi.getter
    def zerotier(self) -> Optional[bool]:
        return pulumi.get(self, "zerotier")


@pulumi.output_type
class GetNetworkAssignmentPoolResult(dict):
    def __init__(__self__, *,
                 end: Optional[str] = None,
                 start: Optional[str] = None):
        if end is not None:
            pulumi.set(__self__, "end", end)
        if start is not None:
            pulumi.set(__self__, "start", start)

    @property
    @pulumi.getter
    def end(self) -> Optional[str]:
        return pulumi.get(self, "end")

    @property
    @pulumi.getter
    def start(self) -> Optional[str]:
        return pulumi.get(self, "start")


@pulumi.output_type
class GetNetworkRouteResult(dict):
    def __init__(__self__, *,
                 target: str,
                 via: Optional[str] = None):
        pulumi.set(__self__, "target", target)
        if via is not None:
            pulumi.set(__self__, "via", via)

    @property
    @pulumi.getter
    def target(self) -> str:
        return pulumi.get(self, "target")

    @property
    @pulumi.getter
    def via(self) -> Optional[str]:
        return pulumi.get(self, "via")


