# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 zerotier_central_token: pulumi.Input[str],
                 zerotier_central_url: pulumi.Input[str]):
        """
        The set of arguments for constructing a Provider resource.
        :param pulumi.Input[str] zerotier_central_token: ZeroTier Central API Token; you can generate a new one at https://my.zerotier.com/account.
        :param pulumi.Input[str] zerotier_central_url: ZeroTier Central API endpoint. Unlikely you'll need to alter this unless you're testing ZeroTier central itself.
        """
        pulumi.set(__self__, "zerotier_central_token", zerotier_central_token)
        pulumi.set(__self__, "zerotier_central_url", zerotier_central_url)

    @property
    @pulumi.getter(name="zerotierCentralToken")
    def zerotier_central_token(self) -> pulumi.Input[str]:
        """
        ZeroTier Central API Token; you can generate a new one at https://my.zerotier.com/account.
        """
        return pulumi.get(self, "zerotier_central_token")

    @zerotier_central_token.setter
    def zerotier_central_token(self, value: pulumi.Input[str]):
        pulumi.set(self, "zerotier_central_token", value)

    @property
    @pulumi.getter(name="zerotierCentralUrl")
    def zerotier_central_url(self) -> pulumi.Input[str]:
        """
        ZeroTier Central API endpoint. Unlikely you'll need to alter this unless you're testing ZeroTier central itself.
        """
        return pulumi.get(self, "zerotier_central_url")

    @zerotier_central_url.setter
    def zerotier_central_url(self, value: pulumi.Input[str]):
        pulumi.set(self, "zerotier_central_url", value)


class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 zerotier_central_token: Optional[pulumi.Input[str]] = None,
                 zerotier_central_url: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        The provider type for the zerotier package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] zerotier_central_token: ZeroTier Central API Token; you can generate a new one at https://my.zerotier.com/account.
        :param pulumi.Input[str] zerotier_central_url: ZeroTier Central API endpoint. Unlikely you'll need to alter this unless you're testing ZeroTier central itself.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProviderArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The provider type for the zerotier package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.

        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 zerotier_central_token: Optional[pulumi.Input[str]] = None,
                 zerotier_central_url: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            if zerotier_central_token is None and not opts.urn:
                raise TypeError("Missing required property 'zerotier_central_token'")
            __props__.__dict__["zerotier_central_token"] = zerotier_central_token
            if zerotier_central_url is None and not opts.urn:
                raise TypeError("Missing required property 'zerotier_central_url'")
            __props__.__dict__["zerotier_central_url"] = zerotier_central_url
        super(Provider, __self__).__init__(
            'zerotier',
            resource_name,
            __props__,
            opts)

    @property
    @pulumi.getter(name="zerotierCentralToken")
    def zerotier_central_token(self) -> pulumi.Output[str]:
        """
        ZeroTier Central API Token; you can generate a new one at https://my.zerotier.com/account.
        """
        return pulumi.get(self, "zerotier_central_token")

    @property
    @pulumi.getter(name="zerotierCentralUrl")
    def zerotier_central_url(self) -> pulumi.Output[str]:
        """
        ZeroTier Central API endpoint. Unlikely you'll need to alter this unless you're testing ZeroTier central itself.
        """
        return pulumi.get(self, "zerotier_central_url")

