// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Zerotier
{
    /// <summary>
    /// The provider type for the zerotier package. By default, resources use package-wide configuration
    /// settings, however an explicit `Provider` instance may be created and passed during resource
    /// construction to achieve fine-grained programmatic control over provider settings. See the
    /// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
    /// </summary>
    [ZerotierResourceType("pulumi:providers:zerotier")]
    public partial class Provider : Pulumi.ProviderResource
    {
        /// <summary>
        /// ZeroTier Central API Token; you can generate a new one at https://my.zerotier.com/account.
        /// </summary>
        [Output("zerotierCentralToken")]
        public Output<string> ZerotierCentralToken { get; private set; } = null!;

        /// <summary>
        /// ZeroTier Central API endpoint. Unlikely you'll need to alter this unless you're testing ZeroTier central itself.
        /// </summary>
        [Output("zerotierCentralUrl")]
        public Output<string> ZerotierCentralUrl { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs args, CustomResourceOptions? options = null)
            : base("zerotier", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// ZeroTier Central API Token; you can generate a new one at https://my.zerotier.com/account.
        /// </summary>
        [Input("zerotierCentralToken", required: true)]
        public Input<string> ZerotierCentralToken { get; set; } = null!;

        /// <summary>
        /// ZeroTier Central API endpoint. Unlikely you'll need to alter this unless you're testing ZeroTier central itself.
        /// </summary>
        [Input("zerotierCentralUrl", required: true)]
        public Input<string> ZerotierCentralUrl { get; set; } = null!;

        public ProviderArgs()
        {
        }
    }
}
