// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Zerotier.Outputs
{

    [OutputType]
    public sealed class GetNetworkAssignIpv6Result
    {
        public readonly bool? Rfc4193;
        public readonly bool? Sixplane;
        public readonly bool? Zerotier;

        [OutputConstructor]
        private GetNetworkAssignIpv6Result(
            bool? rfc4193,

            bool? sixplane,

            bool? zerotier)
        {
            Rfc4193 = rfc4193;
            Sixplane = sixplane;
            Zerotier = zerotier;
        }
    }
}
