// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Zerotier.Outputs
{

    [OutputType]
    public sealed class GetNetworkRouteResult
    {
        public readonly string Target;
        public readonly string? Via;

        [OutputConstructor]
        private GetNetworkRouteResult(
            string target,

            string? via)
        {
            Target = target;
            Via = via;
        }
    }
}
