// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Zerotier.Outputs
{

    [OutputType]
    public sealed class NetworkRoute
    {
        /// <summary>
        /// Network to route for
        /// </summary>
        public readonly string Target;
        /// <summary>
        /// Gateway address
        /// </summary>
        public readonly string? Via;

        [OutputConstructor]
        private NetworkRoute(
            string target,

            string? via)
        {
            Target = target;
            Via = via;
        }
    }
}
