// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Zerotier.Outputs
{

    [OutputType]
    public sealed class NetworkAssignmentPool
    {
        /// <summary>
        /// The last address in the assignment rule. This must be the highest number in the pool. end must also be accompanied by start.
        /// </summary>
        public readonly string? End;
        /// <summary>
        /// The first address in the assignment rule. This must be the lowest number in the pool. `start` must also be accompanied by `end`.
        /// </summary>
        public readonly string? Start;

        [OutputConstructor]
        private NetworkAssignmentPool(
            string? end,

            string? start)
        {
            End = end;
            Start = start;
        }
    }
}
