// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package zerotier

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "zerotier:index/identity:Identity":
		r = &Identity{}
	case "zerotier:index/member:Member":
		r = &Member{}
	case "zerotier:index/network:Network":
		r = &Network{}
	case "zerotier:index/token:Token":
		r = &Token{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:zerotier" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := PkgVersion()
	if err != nil {
		fmt.Printf("failed to determine package version. defaulting to v1: %v\n", err)
	}
	pulumi.RegisterResourceModule(
		"zerotier",
		"index/identity",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zerotier",
		"index/member",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zerotier",
		"index/network",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zerotier",
		"index/token",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"zerotier",
		&pkg{version},
	)
}
