// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package zerotier

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the zerotier package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// ZeroTier Central API Token; you can generate a new one at https://my.zerotier.com/account.
	ZerotierCentralToken pulumi.StringOutput `pulumi:"zerotierCentralToken"`
	// ZeroTier Central API endpoint. Unlikely you'll need to alter this unless you're testing ZeroTier central itself.
	ZerotierCentralUrl pulumi.StringOutput `pulumi:"zerotierCentralUrl"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ZerotierCentralToken == nil {
		return nil, errors.New("invalid value for required argument 'ZerotierCentralToken'")
	}
	if args.ZerotierCentralUrl == nil {
		return nil, errors.New("invalid value for required argument 'ZerotierCentralUrl'")
	}
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:zerotier", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// ZeroTier Central API Token; you can generate a new one at https://my.zerotier.com/account.
	ZerotierCentralToken string `pulumi:"zerotierCentralToken"`
	// ZeroTier Central API endpoint. Unlikely you'll need to alter this unless you're testing ZeroTier central itself.
	ZerotierCentralUrl string `pulumi:"zerotierCentralUrl"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// ZeroTier Central API Token; you can generate a new one at https://my.zerotier.com/account.
	ZerotierCentralToken pulumi.StringInput
	// ZeroTier Central API endpoint. Unlikely you'll need to alter this unless you're testing ZeroTier central itself.
	ZerotierCentralUrl pulumi.StringInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
