// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// ZeroTier Central API Token; you can generate a new one at https://my.zerotier.com/account.
func GetZerotierCentralToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "zerotier:zerotierCentralToken")
}

// ZeroTier Central API endpoint. Unlikely you'll need to alter this unless you're testing ZeroTier central itself.
func GetZerotierCentralUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "zerotier:zerotierCentralUrl")
}
