// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface GerNetworkAssignIpv4 {
    zerotier?: boolean;
}

export interface GerNetworkAssignIpv4Args {
    zerotier?: pulumi.Input<boolean>;
}

export interface GerNetworkAssignIpv6Args {
    rfc4193?: pulumi.Input<boolean>;
    sixplane?: pulumi.Input<boolean>;
    zerotier?: pulumi.Input<boolean>;
}

export interface GerNetworkAssignIpv6 {
    rfc4193?: boolean;
    sixplane?: boolean;
    zerotier?: boolean;
}

export interface GerNetworkAssignmentPoolArgs {
    end?: pulumi.Input<string>;
    start?: pulumi.Input<string>;
}

export interface GerNetworkAssignmentPool {
    end?: string;
    start?: string;
}

export interface GerNetworkRoute {
    target: string;
    via?: string;
}

export interface GerNetworkRouteArgs {
    target: pulumi.Input<string>;
    via?: pulumi.Input<string>;
}

export interface NetworkAssignIpv4 {
    zerotier?: pulumi.Input<boolean>;
}

export interface NetworkAssignIpv6 {
    rfc4193?: pulumi.Input<boolean>;
    sixplane?: pulumi.Input<boolean>;
    zerotier?: pulumi.Input<boolean>;
}

export interface NetworkAssignmentPool {
    /**
     * The last address in the assignment rule. This must be the highest number in the pool. end must also be accompanied by start.
     */
    end?: pulumi.Input<string>;
    /**
     * The first address in the assignment rule. This must be the lowest number in the pool. `start` must also be accompanied by `end`.
     */
    start?: pulumi.Input<string>;
}

export interface NetworkRoute {
    /**
     * Network to route for
     */
    target: pulumi.Input<string>;
    /**
     * Gateway address
     */
    via?: pulumi.Input<string>;
}

