// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Zerotier.Inputs
{

    public sealed class NetworkAssignmentPoolGetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The last address in the assignment rule. This must be the highest number in the pool. end must also be accompanied by start.
        /// </summary>
        [Input("end")]
        public Input<string>? End { get; set; }

        /// <summary>
        /// The first address in the assignment rule. This must be the lowest number in the pool. `start` must also be accompanied by `end`.
        /// </summary>
        [Input("start")]
        public Input<string>? Start { get; set; }

        public NetworkAssignmentPoolGetArgs()
        {
        }
    }
}
