// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Zerotier.Inputs
{

    public sealed class NetworkRouteGetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Network to route for
        /// </summary>
        [Input("target", required: true)]
        public Input<string> Target { get; set; } = null!;

        /// <summary>
        /// Gateway address
        /// </summary>
        [Input("via")]
        public Input<string>? Via { get; set; }

        public NetworkRouteGetArgs()
        {
        }
    }
}
